### ISSUE TITLE
reset password - still pending

### ISSUE THREAD

**Issue by johantino** [NewCircleMovement/ncm#27]
Besked fra Tom Kise da han klikkede glemt password:
Når jeg forsøger skifte password, får jeg “Reset password token is invalid”

Laugrits prøvede også idag. fik ingen mail.

(sender god vind til dette ;) )

**Comment by kbjerring** [comment]
Dette er fixet. Har lige testet.

**Comment by johantino** [comment]
besked fra Tom , han har netop prøvet igen: Samme fejl. Reset password token is invali
